apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    role: {{ .Values.app.role }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      role: {{ .Values.app.role }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        role: {{ .Values.app.role }}
    spec:
      containers:
        - name: {{ .Values.app.role }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    role: {{ .Values.app.role }}
spec:
  selector:
    app: {{ .Values.app.name }}
    role: {{ .Values.app.role }}
  ports:
    - name: http
      port: {{ .Values.app.servicePort | default .Values.app.containerPort }}
      targetPort: {{ .Values.app.containerPort }}
  type: ClusterIP

{{- if .Values.app.createRoute }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}-route
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    role: {{ .Values.app.role }}
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}-svc
    weight: 100
  port:
    targetPort: http
  path: /
  wildcardPolicy: None
{{- end }}