apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: reto-open
    role: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: reto-open
      role: frontend
  template:
    metadata:
      labels:
        app: reto-open
        role: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: ROLE
              value: "frontend"
            - name: BACKEND_API_URL
              value: {{ .Values.urls.backendApi | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: reto-open
    role: frontend
spec:
  selector:
    app: reto-open
    role: frontend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
  namespace: {{ .Values.namespace }}
  labels:
    app: reto-open
    role: frontend
spec:
  to:
    kind: Service
    name: frontend-svc
    weight: 100
  port:
    targetPort: http
  path: /
  wildcardPolicy: None