apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: reto-open
    role: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: reto-open
      role: frontend
  template:
    metadata:
      labels:
        app: reto-open
        role: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: reto-open
    role: frontend
spec:
  selector:
    app: reto-open
    role: frontend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  type: ClusterIP