apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-micro-a-to-micro-b-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: reto-open
    role: frontend
spec:
  podSelector:
    matchLabels:
      app: reto-open
      role: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.containerPort }}