apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-micro-a-to-micro-b-ingress-{{ .Values.app.role }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    role: {{ .Values.app.role }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
      role: {{ .Values.app.role }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - protocol: TCP
          port: {{ .Values.app.containerPort }}

    - from:
        - podSelector: {}   # cualquier pod del namespace
      ports:
        - protocol: TCP

          port: {{ .Values.app.containerPort }}
