name: reto-open
namespace: stnvivanco92-dev

frontend:
  image: "savivancofi/frontend:latest"      # luego actualizas la tag
  replicas: 1
  containerPort: 3000

backendApi:
  image: "savivancofi/backend-api:latest"
  replicas: 1
  containerPort: 8080

backendData:
  image: "savivancofi/backend-data:latest"
  replicas: 1
  containerPort: 8081

database:
  image: "postgres:16"
  containerPort: 5432
  storageSize: 1Gi
  dbName: retobdd
  dbUser: retobdd_user
  dbPassword: retobdd_user

urls:
  backendApi: "http://backend-api-svc:8080"
  backendData: "http://backend-data-svc:8081"
  databaseHost: "db-svc"