name: reto-open
namespace: stnvivanco92-dev

frontend:
  image: "savivancofi/frontend"
  tag: "v1"                 # cuando subas la imagen al Docker Hub, usas aqu√≠ la tag real
  replicas: 1
  containerPort: 3000       # tu contenedor de frontend debe escuchar en este puerto

backendApi:
  image: "savivancofi/backend-api"
  tag: "v1"
  replicas: 1
  containerPort: 8080

backendData:
  image: "savivancofi/backend-data"
  tag: "v1"
  replicas: 1
  containerPort: 8081

database:
  image: "postgres"
  tag: "16"
  containerPort: 5432
  storageSize: 1Gi
  dbName: retobdd
  dbUser: retobdd_user
  dbPassword: retobdd_user

urls:
  backendApi: "http://backend-api-svc:8080"
  backendData: "http://backend-data-svc:8081"
  databaseHost: "db-svc"